# Generated by Django 3.2.3 on 2021-07-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0002_alter_heart_oldpeak'),
    ]

    operations = [
        migrations.AddField(
            model_name='heart',
            name='patient_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='heart',
            name='age',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='ca',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='chol',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='cp',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='exang',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='fbs',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='oldpeak',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='restecg',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='sex',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='slope',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='target',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='thal',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='thalach',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='heart',
            name='trestbps',
            field=models.IntegerField(default=''),
        ),
    ]
