# Generated by Django 3.2.3 on 2021-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeartApp', '0003_auto_20210724_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heart',
            old_name='patient_name',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='heart',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='heart',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
    ]
